#!/usr/bin/env python3
"""Reject mixed or malformed U-Boot SPL/proper artifacts."""

import argparse
import pathlib
import re
import struct
import zlib


EGON_STAMP = 0x5F0A6C39
UIMAGE_MAGIC = 0x27051956


def fail(message: str) -> None:
    raise SystemExit(f"MAINLINE_UBOOT_VERIFY_FAILED: {message}")


def u32le(data: bytes, offset: int) -> int:
    return struct.unpack_from("<I", data, offset)[0]


def build_stamp(data: bytes, prefix: bytes, version: str) -> bytes:
    pattern = re.escape(prefix + version.encode("ascii")) + rb" \(([^\r\n\x00]+)\)"
    match = re.search(pattern, data)
    if not match:
        fail(f"missing {prefix.decode('ascii')}{version} build identity")
    return match.group(1)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--spl", required=True, type=pathlib.Path)
    parser.add_argument("--uboot-bin", required=True, type=pathlib.Path)
    parser.add_argument("--uboot-img", required=True, type=pathlib.Path)
    parser.add_argument("--uboot-elf", required=True, type=pathlib.Path)
    parser.add_argument("--version", required=True)
    parser.add_argument("--board", required=True)
    args = parser.parse_args()

    build_dir = args.spl.parent.parent.resolve()
    for artifact in (args.uboot_bin, args.uboot_img, args.uboot_elf):
        if artifact.parent.resolve() != build_dir:
            fail("SPL and U-Boot proper paths are not from one build directory")
    config_path = build_dir / ".config"
    version_path = build_dir / "include/generated/version_autogenerated.h"
    if not config_path.is_file() or not version_path.is_file():
        fail("U-Boot build identity files are missing")
    config = config_path.read_text(encoding="ascii")
    version_header = version_path.read_text(encoding="ascii")
    if f'#define PLAIN_VERSION "{args.version}"' not in version_header:
        fail("generated U-Boot version does not match the required version")
    required_config = (
        "CONFIG_SPL=y",
        "CONFIG_SPL_SPI_SUNXI=y",
        "CONFIG_MACH_SUN8I_R528=y",
        f'CONFIG_DEFAULT_DEVICE_TREE="{args.board}"',
    )
    for setting in required_config:
        if setting not in config.splitlines():
            fail(f"required mainline setting is absent: {setting}")
    if "CONFIG_ANDROID_BOOT_IMAGE=y" in config.splitlines():
        fail("Android boot-image support is forbidden in the mainline path")
    bootcommand = next(
        (line for line in config.splitlines() if line.startswith("CONFIG_BOOTCOMMAND=")),
        "",
    )
    if "${fel_booted}" not in bootcommand or "bootm 0x44000000" not in bootcommand:
        fail("U-Boot proper does not select the mainline RAM installer on FEL boot")

    spl = args.spl.read_bytes()
    proper = args.uboot_bin.read_bytes()
    image = args.uboot_img.read_bytes()
    elf = args.uboot_elf.read_bytes()

    if len(spl) < 96 or len(spl) % 512:
        fail("sunxi-spl.bin length is not a valid 512-byte-aligned eGON image")
    if spl[4:12] != b"eGON.BT0":
        fail("sunxi-spl.bin has no eGON.BT0 header")
    if (u32le(spl, 0) & 0xFF000000) != 0xEA000000:
        fail("sunxi-spl.bin has no ARM branch at the eGON entry")
    if spl[20:23] != b"SPL":
        fail("sunxi-spl.bin has no mainline SPL header signature")
    egon_length = u32le(spl, 16)
    if egon_length != len(spl):
        fail(f"eGON length {egon_length} does not match SPL size {len(spl)}")
    stored_checksum = u32le(spl, 12)
    checksum_image = bytearray(spl)
    struct.pack_into("<I", checksum_image, 12, EGON_STAMP)
    calculated_checksum = sum(
        struct.unpack_from("<I", checksum_image, offset)[0]
        for offset in range(0, egon_length, 4)
    ) & 0xFFFFFFFF
    if calculated_checksum != stored_checksum:
        fail(
            f"bad eGON checksum: stored=0x{stored_checksum:08x} "
            f"calculated=0x{calculated_checksum:08x}"
        )
    dt_offset = u32le(spl, 32)
    if not 0 < dt_offset < min(len(spl), 4096):
        fail("eGON header has no valid device-tree name")
    dt_name = spl[dt_offset:].split(b"\0", 1)[0].decode("ascii", "strict")
    if dt_name != args.board:
        fail(f"SPL target is {dt_name!r}, expected {args.board!r}")

    spl_stamp = build_stamp(spl, b"U-Boot SPL ", args.version)
    proper_stamp = build_stamp(proper, b"U-Boot ", args.version)
    if spl_stamp != proper_stamp:
        fail(
            "SPL and U-Boot proper were not produced by the same build: "
            f"{spl_stamp.decode()} != {proper_stamp.decode()}"
        )

    if len(image) < 64 or struct.unpack_from(">I", image, 0)[0] != UIMAGE_MAGIC:
        fail("u-boot.img is not a legacy mainline U-Boot image")
    stored_header_crc = struct.unpack_from(">I", image, 4)[0]
    header = bytearray(image[:64])
    struct.pack_into(">I", header, 4, 0)
    if zlib.crc32(header) & 0xFFFFFFFF != stored_header_crc:
        fail("u-boot.img header CRC is invalid")
    payload_size = struct.unpack_from(">I", image, 12)[0]
    load_address = struct.unpack_from(">I", image, 16)[0]
    entry_address = struct.unpack_from(">I", image, 20)[0]
    stored_data_crc = struct.unpack_from(">I", image, 24)[0]
    payload = image[64:64 + payload_size]
    if payload != proper or len(payload) != payload_size:
        fail("u-boot.img payload is not the supplied same-build u-boot.bin")
    if zlib.crc32(payload) & 0xFFFFFFFF != stored_data_crc:
        fail("u-boot.img data CRC is invalid")
    image_name = image[32:64].split(b"\0", 1)[0].decode("ascii", "strict")
    if image_name != f"U-Boot {args.version} for sunxi board":
        fail(f"unexpected u-boot.img name {image_name!r}")

    if elf[:4] != b"\x7fELF" or elf[4] != 1 or elf[5] != 1:
        fail("u-boot is not a 32-bit little-endian ELF")
    elf_entry = u32le(elf, 24)
    text_base = int(
        next(line.split("=", 1)[1] for line in config.splitlines()
             if line.startswith("CONFIG_TEXT_BASE=")),
        0,
    )
    if load_address != entry_address or entry_address != elf_entry:
        fail(
            f"proper load/entry mismatch: load=0x{load_address:08x}, "
            f"image-entry=0x{entry_address:08x}, elf-entry=0x{elf_entry:08x}"
        )
    if elf_entry != text_base:
        fail(
            f"proper entry 0x{elf_entry:08x} does not match "
            f"CONFIG_TEXT_BASE 0x{text_base:08x}"
        )

    print(f"Verified mainline U-Boot {args.version} same-build pair")
    print(f"  SPL: eGON.BT0, {len(spl)} bytes, board={dt_name}")
    print(f"  proper: {len(proper)} bytes, load/entry=0x{entry_address:08x}")
    print(f"  build identity: {spl_stamp.decode('ascii')}")


if __name__ == "__main__":
    main()

